### PR TITLE
extinfo extensions

### PR DESCRIPTION
**Pull request by tpoechtrager**
This patch makes it possible to request `suicides, shotdamage, damage, explosivedamage, hits, misses and shots` too via `EXT_PLAYERSTATS`.

### CODE REVIEW

**Comment by pisto** [comment]
no, should be done as a lua module.

**Comment by tpoechtrager** [comment]
??? I have added it in Lua and in C++...

**Comment by pisto** [comment]
Right, I rushed through it. But remove the C++ part, it's not needed.

**Comment by pisto** [comment]
I will probably need to make a more organized lua module for extinfo with options and all.

**Comment by tpoechtrager** [comment]
It was needed when I removed the extinfo Lua module from `script/load.d/`, are you sure I should really remove it from `extinfo.h`?

**Comment by pisto** [comment]
Yes, I want to maintain c++ source compatibility. Ideally sapghettimod should behave as a vanilla server if all the lua modules are removed. I also will move at some point your extinfo fingerprint (the -4 thing) to lua.

**Comment by tpoechtrager** [comment]
Should be ok now?

**Comment by pisto** [comment]
Sorry, I'm distracted, so I didn't see that it actually needs some extra fields in the client structure. I don't want that either, there's the clientinfo.extra table for that. I can code that later myself, or it is a nice exercise if you want to use spaghetti hooks and stuff.

**Comment by tpoechtrager** [comment]
It's the same thing as in SuckerServ / old Hopmod.
If you are not happy with it in gamestate, then please move it to that extra field.

**Comment by pisto** [comment]
yes, that's what I will do.

**Comment by tpoechtrager** [comment]
Thanks :smile:

**Comment by pisto** [comment]
Can you please explain exactly what hits, misses and shots should count? It's not too clear what you want to do with them (wtf old_hits?). How should they behave when the shot/explode/damage event is cancelled? Mind that there are various way that a damage event can be cancelled: you can skip the processing of hits with the hooks "shot" and "explode", you can suppress damage by hooking "dodamage" but letting other effects (such as pushback) happen, or you can suppress them (independently of actual damage) by hooking "damageeffects".

**Comment by pisto** [comment]
Also, maybe it's too late now, but I really dislike that you modify existent extinfo messages instead of using a new extinfo code. It's way neater to have a new EXT_* thing, and your mod would use that to acquire more detailed info.

**Comment by tpoechtrager** [comment]
> Also, maybe it's too late now, but I really dislike that you modify existent extinfo messages instead of using a new extinfo code. It's way neater to have a new EXT_* thing, and your mod would use that to acquire more detailed info.

To be able to request everything in one go and to reduce the packet count. The fact that every player has its own packet sucks already enough. I will keep it the way it is.

> Can you please explain exactly what hits, misses and shots should count? It's not too clear what you want to do with them (wtf old_hits?). How should they behave when the shot/explode/damage event is cancelled? Mind that there are various way that a damage event can be cancelled: you can skip the processing of hits with the hooks "shot" and "explode", you can suppress damage by hooking "dodamage" but letting other effects (such as pushback) happen, or you can suppress them (independently of actual damage) by hooking "damageeffects".

Don't blame me, I took it from hopmod and it worked the way it should when I have tested it. Canceled events shouldn't be counted, only when real damage happens (not just "effects").

**Comment by tpoechtrager** [comment]
You could make

`local extended = req:remaining() and req:getint() > 0`

a bit more precise and replace it with:

`local extended = req:remaining() and req:getint() == 0xC8343F2`

**Pull request closed without merging**
